services:
  app:
    container_name: strapi_app
    build:
      context: .
      dockerfile: infra/app/Dockerfile.prod
    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT:-postgres}
      DATABASE_HOST: postgres
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_NAME: ${DATABASE_NAME:-strapi}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-strapi}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-strapi}
      JWT_SECRET: ${JWT_SECRET:-strapi}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET:-strapi}
      APP_KEYS: ${APP_KEYS:-}
      NODE_ENV: ${NODE_ENV:-production}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi
    depends_on:
      - postgres

  postgres:
    container_name: postgres_strapi
    restart: unless-stopped
    env_file: .env
    image: postgres:14.0-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./data:/var/lib/postgres/data/ # if you want to use a bind folder

    ports:
      - "5432:5432"
    networks:
      - strapi

networks:
  strapi:
    name: Strapi
    driver: bridge
